#!/usr/bin/env python3
from time import sleep 
from loading import ft_progress 

listy = range(1000)
ret = 0
for elem in ft_progress(listy):
    ret += (elem + 3) % 5
    sleep(0.01)
print()
print(ret)
